### ISSUE TITLE
上传图片有bug 

### ISSUE THREAD

**Issue by TengFeiWu** [youlookwhat/ByWebView#60]
如果点上传图片， 进入相册 返回，无法进行二次上传

**Comment by youlookwhat** [comment]
我刚用我手上的oppo android12 的手机测试是可以的，你这个可能是部分手机的适配问题？

这个库不是主要处理这个的，这个只是给一个示例，如果用到商业中的话，具体的上传兼容性和业务逻辑还请和h5那边的同事联调哈。

**Comment by TengFeiWu** [comment]
我用的vivo x30 Pro

**Comment by youlookwhat** [comment]
这个问题暂时不处理了，因为主要是h5那边的问题，而且项目里只是提供示例可以这样做，是一个很小的demo，如果要用在实际项目中h5还需要考虑很多情况。
